### ISSUE TITLE
Wouldn't it be cool, to use jenkins pipeline instead of ant

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [sebastianbergmann/php-jenkins-template#127]
Advantages
 - The Pipeline script will be in same Version control System as my Project.
 - Each step's log can easily be followed in Jenkins Blue Ocean, making it easier to find the relevant entries if one step failed or whatever..

**Comment by lferro9000** [comment]
You can for the most part:

https://gist.github.com/Yuav/435f29cad03bf0006a85d31f2350f7b4

There is in the end two elements that are commented out. The clover one can be uncommented as it works fine now. The Crap4j still doesn't work (but you get the information on the phpdox etc).

The other thing that isn't working is the pdepends graphs as they are (in the original "template") added to the description. That doesn't work with Jenkins 2 due to the fact that it escapes everything (even editing the job template doesn't work).

Some sort of html needs to be generated to allow a plain htmlpublish for it.

![jenkins-pipelines](https://user-images.githubusercontent.com/2652260/28726463-421eb006-73b9-11e7-86e2-00608161f601.png)

**Comment by michaelpporter** [comment]
I too use pipeline for my new builds and testing. Working on a writeup currently.

**Comment by paulcanning** [comment]
Which plugin is it to use pipelines and get that stage view? I looked in the plugin directory, but there are a lot of plugins with the term pipelines in the name.

**Comment by Guite** [comment]
https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin
https://plugins.jenkins.io/pipeline-stage-view

**Comment by paulcanning** [comment]
> https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin
> https://plugins.jenkins.io/pipeline-stage-view

Thank you. And which plugin lets me actually run pipeline scripts?
